-- Swayimg Configuration
-- Colors loaded from theme system (generated by apply-theme.sh)

-- Load theme colors (generated file)
local colors_path = os.getenv("HOME") .. "/.config/swayimg/colors.lua"
local ok, c = pcall(dofile, colors_path)
if not ok then
  -- Fallback: neutral dark defaults if theme file missing
  c = {
    bg = 0xff1a1a2e, bg_alt = 0xff1e1e2e, fg = 0xffe0e1e5, fg_dim = 0xffb4a7d6,
    primary = 0xff8844ff, secondary = 0xff00aaff, accent = 0xff00ff88,
    surface = 0xff2a2a40, warn = 0xffffaa00, crit = 0xffff0088, pink = 0xffff44aa,
  }
end

-- General
swayimg.set_mode("viewer")
swayimg.enable_antialiasing(true)
swayimg.enable_decoration(false)
swayimg.enable_overlay(false)
swayimg.enable_exif_orientation(true)
swayimg.set_dnd_button("MouseRight")

-- Image list
swayimg.imagelist.set_order("numeric")
swayimg.imagelist.enable_reverse(false)
swayimg.imagelist.enable_recursive(false)
swayimg.imagelist.enable_adjacent(true)
swayimg.imagelist.enable_fsmon(true)

-- Text overlay
swayimg.text.set_font("JetBrainsMono Nerd Font")
swayimg.text.set_size(16)
swayimg.text.set_spacing(2)
swayimg.text.set_padding(12)
swayimg.text.set_foreground(c.accent)
swayimg.text.set_background(c.bg - 0x33000000)  -- bg with slight transparency
swayimg.text.set_shadow(0x80000000)
swayimg.text.set_timeout(3)
swayimg.text.set_status_timeout(2)

-- Viewer mode
swayimg.viewer.set_default_scale("optimal")
swayimg.viewer.set_default_position("center")
swayimg.viewer.set_drag_button("MouseLeft")
swayimg.viewer.set_window_background(c.bg)
swayimg.viewer.set_image_chessboard(16, c.surface, c.bg_alt)
swayimg.viewer.enable_centering(true)
swayimg.viewer.enable_loop(true)
swayimg.viewer.limit_preload(2)
swayimg.viewer.limit_history(2)
swayimg.viewer.set_mark_color(c.primary)

-- Viewer text overlays
swayimg.viewer.set_text("topleft", {
  "{name}",
  "{format} | {sizehr}",
})
swayimg.viewer.set_text("topright", {
  "{list.index} / {list.total}",
  "{frame.width}x{frame.height}",
})
swayimg.viewer.set_text("bottomleft", {
  "{scale}",
})

-- Slideshow
swayimg.slideshow.set_timeout(5)
swayimg.slideshow.set_default_scale("fit")
swayimg.slideshow.set_window_background(c.bg)
swayimg.slideshow.limit_history(1)
swayimg.slideshow.set_text("topleft", { "{name}" })

-- Gallery mode
swayimg.gallery.set_aspect("fill")
swayimg.gallery.set_thumb_size(220)
swayimg.gallery.set_padding_size(6)
swayimg.gallery.set_border_size(3)
swayimg.gallery.set_border_color(c.primary)
swayimg.gallery.set_selected_scale(1.1)
swayimg.gallery.set_selected_color(c.surface)
swayimg.gallery.set_unselected_color(c.bg_alt)
swayimg.gallery.set_window_color(c.bg)
swayimg.gallery.limit_cache(150)
swayimg.gallery.enable_preload(true)
swayimg.gallery.enable_pstore(false)
swayimg.gallery.set_text("topleft", { "{name}" })
swayimg.gallery.set_text("topright", { "{list.index} / {list.total}" })

-- Re-fit on window resize (good for tiling)
swayimg.on_window_resize(function()
  swayimg.viewer.set_fix_scale("optimal")
end)

-- Gallery: Enter opens in viewer
swayimg.gallery.on_key("Return", function()
  swayimg.set_mode("viewer")
end)

------------------------------------------------------------
-- Vim-style keybindings — Viewer
------------------------------------------------------------

-- Quit
swayimg.viewer.on_key("q", function() swayimg.exit() end)
swayimg.viewer.on_key("Escape", function() swayimg.exit() end)

-- Navigation: next/prev image
swayimg.viewer.on_key("l", function() swayimg.viewer.switch_image("next") end)
swayimg.viewer.on_key("h", function() swayimg.viewer.switch_image("prev") end)
swayimg.viewer.on_key("Right", function() swayimg.viewer.switch_image("next") end)
swayimg.viewer.on_key("Left", function() swayimg.viewer.switch_image("prev") end)

-- Pan with j/k
swayimg.viewer.on_key("j", function()
  local wnd = swayimg.get_window_size()
  local pos = swayimg.viewer.get_position()
  swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y - wnd.height / 10))
end)
swayimg.viewer.on_key("k", function()
  local wnd = swayimg.get_window_size()
  local pos = swayimg.viewer.get_position()
  swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y + wnd.height / 10))
end)

-- Zoom
swayimg.viewer.on_key("plus", function()
  local scale = swayimg.viewer.get_scale()
  swayimg.viewer.set_abs_scale(scale * 1.2)
end)
swayimg.viewer.on_key("minus", function()
  local scale = swayimg.viewer.get_scale()
  swayimg.viewer.set_abs_scale(scale / 1.2)
end)
swayimg.viewer.on_key("equal", function()
  swayimg.viewer.set_default_scale("optimal")
  swayimg.viewer.set_fix_scale("optimal")
end)

-- Zoom with scroll
swayimg.viewer.on_mouse("ScrollUp", function()
  local pos = swayimg.get_mouse_pos()
  local scale = swayimg.viewer.get_scale()
  swayimg.viewer.set_abs_scale(scale * 1.1, pos.x, pos.y)
end)
swayimg.viewer.on_mouse("ScrollDown", function()
  local pos = swayimg.get_mouse_pos()
  local scale = swayimg.viewer.get_scale()
  swayimg.viewer.set_abs_scale(scale / 1.1, pos.x, pos.y)
end)

-- Actual size (1:1)
swayimg.viewer.on_key("0", function()
  swayimg.viewer.set_abs_scale(1.0)
end)

-- Toggle gallery mode
swayimg.viewer.on_key("g", function()
  swayimg.set_mode("gallery")
end)

-- Toggle slideshow
swayimg.viewer.on_key("s", function()
  swayimg.set_mode("slideshow")
end)

-- Toggle info overlay
swayimg.viewer.on_key("i", function()
  swayimg.text.toggle_timeout()
end)

-- Mark/unmark image
swayimg.viewer.on_key("m", function()
  swayimg.viewer.toggle_mark()
end)

------------------------------------------------------------
-- Vim-style keybindings — Gallery
------------------------------------------------------------
swayimg.gallery.on_key("q", function() swayimg.exit() end)
swayimg.gallery.on_key("Escape", function() swayimg.exit() end)
swayimg.gallery.on_key("h", function() swayimg.gallery.switch_image("left") end)
swayimg.gallery.on_key("j", function() swayimg.gallery.switch_image("down") end)
swayimg.gallery.on_key("k", function() swayimg.gallery.switch_image("up") end)
swayimg.gallery.on_key("l", function() swayimg.gallery.switch_image("right") end)
swayimg.gallery.on_key("Left", function() swayimg.gallery.switch_image("left") end)
swayimg.gallery.on_key("Down", function() swayimg.gallery.switch_image("down") end)
swayimg.gallery.on_key("Up", function() swayimg.gallery.switch_image("up") end)
swayimg.gallery.on_key("Right", function() swayimg.gallery.switch_image("right") end)
