-- Theme colors — Generated by theme system (do not edit manually)
return {
  bg = "#1a1a2e",
  bg_alt = "#1e1e2e",
  fg = "#e0e1e5",
  fg_dim = "#b4a7d6",
  primary = "#8844ff",
  secondary = "#00aaff",
  accent = "#00ff88",
  border = "#8844ff",
  warn = "#ffaa00",
  crit = "#ff0088",
  surface = "#2a2a40",
  pink = "#ff44aa",
}
