-- Theme colors — Generated by theme system (do not edit manually)
return {
  bg = "#1e1e2e",
  bg_alt = "#313244",
  fg = "#cdd6f4",
  fg_dim = "#a6adc8",
  primary = "#cba6f7",
  secondary = "#89b4fa",
  accent = "#a6e3a1",
  border = "#cba6f7",
  warn = "#f9e2af",
  crit = "#f38ba8",
  surface = "#45475a",
  pink = "#f5c2e7",
}
