# Dracula
THEME_NAME="dracula"
COLOR_BG="#282a36"
COLOR_BG_ALT="#44475a"
COLOR_FG="#f8f8f2"
COLOR_FG_DIM="#6272a4"
COLOR_PRIMARY="#bd93f9"
COLOR_SECONDARY="#8be9fd"
COLOR_ACCENT="#50fa7b"
COLOR_BORDER="#bd93f9"
COLOR_WARN="#f1fa8c"
COLOR_CRIT="#ff5555"
COLOR_SURFACE="#44475a"
COLOR_PINK="#ff79c6"
COLOR_TERM_FG="#f8f8f2"
COLOR_BG_ALPHA="0.90"
