# Hyprlock colors — Generated by theme system
$clock_color = rgb({{COLOR_ACCENT_RAW}})
$date_color = rgb({{COLOR_PRIMARY_RAW}})
$prompt_color = rgb({{COLOR_SECONDARY_RAW}})
$fail_color = rgb({{COLOR_CRIT_RAW}})
$font_color = rgb({{COLOR_FG_RAW}})
