# Kitty colors — Generated by theme system
foreground {{COLOR_TERM_FG}}
background {{COLOR_BG}}
background_opacity {{COLOR_BG_ALPHA}}
cursor {{COLOR_ACCENT}}
cursor_text_color {{COLOR_BG}}
selection_foreground {{COLOR_BG}}
selection_background {{COLOR_PRIMARY}}
url_color {{COLOR_SECONDARY}}

# Tab bar
active_tab_foreground {{COLOR_BG}}
active_tab_background {{COLOR_PRIMARY}}
inactive_tab_foreground {{COLOR_FG_DIM}}
inactive_tab_background {{COLOR_BG_ALT}}

# ANSI colors (inherited by nvim, btop, and all TUI apps)
# Black
color0 {{COLOR_BG_ALT}}
color8 {{COLOR_SURFACE}}

# Red
color1 {{COLOR_CRIT}}
color9 {{COLOR_CRIT}}

# Green
color2 {{COLOR_ACCENT}}
color10 {{COLOR_ACCENT}}

# Yellow
color3 {{COLOR_WARN}}
color11 {{COLOR_WARN}}

# Blue
color4 {{COLOR_PRIMARY}}
color12 {{COLOR_PRIMARY}}

# Magenta
color5 {{COLOR_PINK}}
color13 {{COLOR_PINK}}

# Cyan
color6 {{COLOR_SECONDARY}}
color14 {{COLOR_SECONDARY}}

# White
color7 {{COLOR_FG}}
color15 {{COLOR_FG}}
