# lsd color theme — Generated by theme system
user: {{COLOR_PRIMARY}}
group: {{COLOR_SECONDARY}}
permission:
  read: {{COLOR_ACCENT}}
  write: {{COLOR_WARN}}
  exec: {{COLOR_CRIT}}
  exec-sticky: {{COLOR_PINK}}
  no-access: {{COLOR_FG_DIM}}
  octal: {{COLOR_FG_DIM}}
  acl: {{COLOR_PRIMARY}}
  context: {{COLOR_SECONDARY}}
date:
  hour-old: {{COLOR_FG}}
  day-old: {{COLOR_FG_DIM}}
  older: {{COLOR_SURFACE}}
size:
  none: {{COLOR_FG_DIM}}
  small: {{COLOR_ACCENT}}
  medium: {{COLOR_WARN}}
  large: {{COLOR_CRIT}}
inode:
  valid: {{COLOR_FG_DIM}}
  invalid: {{COLOR_CRIT}}
links:
  valid: {{COLOR_SECONDARY}}
  invalid: {{COLOR_CRIT}}
tree-edge: {{COLOR_SURFACE}}
git-status:
  default: {{COLOR_FG_DIM}}
  unmodified: {{COLOR_FG_DIM}}
  ignored: {{COLOR_FG_DIM}}
  new-in-index: {{COLOR_ACCENT}}
  new-in-workdir: {{COLOR_ACCENT}}
  typechange: {{COLOR_WARN}}
  deleted: {{COLOR_CRIT}}
  renamed: {{COLOR_SECONDARY}}
  modified: {{COLOR_WARN}}
  conflicted: {{COLOR_CRIT}}
