-- Theme colors — Generated by theme system (do not edit manually)
return {
  bg = "{{COLOR_BG}}",
  bg_alt = "{{COLOR_BG_ALT}}",
  fg = "{{COLOR_FG}}",
  fg_dim = "{{COLOR_FG_DIM}}",
  primary = "{{COLOR_PRIMARY}}",
  secondary = "{{COLOR_SECONDARY}}",
  accent = "{{COLOR_ACCENT}}",
  border = "{{COLOR_BORDER}}",
  warn = "{{COLOR_WARN}}",
  crit = "{{COLOR_CRIT}}",
  surface = "{{COLOR_SURFACE}}",
  pink = "{{COLOR_PINK}}",
}
