/* Rofi colors — Generated by theme system */
* {
    bg:           {{COLOR_BG}}90;
    bg-alt:       {{COLOR_BG_ALT}}ff;
    fg:           {{COLOR_ACCENT}};
    fg-dim:       {{COLOR_FG_DIM}};
    border-color: {{COLOR_PRIMARY}};
    accent:       {{COLOR_SECONDARY}};
    urgent:       {{COLOR_CRIT}};
}
