# Starship color palette — Generated by theme system
[palettes.theme]
color_bg = "{{COLOR_BG}}"
color_fg = "{{COLOR_FG}}"
color_dim = "{{COLOR_FG_DIM}}"
color_orange = "{{COLOR_WARN}}"
color_red = "{{COLOR_CRIT}}"
color_green = "{{COLOR_ACCENT}}"
color_blue = "{{COLOR_SECONDARY}}"
color_purple = "{{COLOR_PRIMARY}}"
color_pink = "{{COLOR_PINK}}"
color_surface = "{{COLOR_SURFACE}}"
