/* SwayNC style — Generated by theme system */
.control-center {
  background: {{COLOR_BG}}f2;
  border: 2px solid {{COLOR_PRIMARY}};
  border-radius: 16px;
  margin: 8px;
  padding: 12px;
}

.notification {
  background: {{COLOR_BG_ALT}};
  border: 1px solid {{COLOR_SURFACE}};
  border-radius: 12px;
  margin: 4px 0;
  padding: 8px 12px;
  color: {{COLOR_FG}};
}

.notification-content {
  color: {{COLOR_FG}};
}

.notification .summary {
  color: {{COLOR_ACCENT}};
  font-weight: bold;
}

.notification .body {
  color: {{COLOR_FG_DIM}};
}

.notification .close-button {
  background: {{COLOR_CRIT}};
  color: {{COLOR_BG}};
  border-radius: 50%;
  min-width: 20px;
  min-height: 20px;
}

.notification.critical {
  border-color: {{COLOR_CRIT}};
}

.notification.low {
  border-color: {{COLOR_SURFACE}};
}

.widget-title {
  color: {{COLOR_PRIMARY}};
  font-weight: bold;
  font-size: 14px;
}

.widget-dnd {
  color: {{COLOR_FG}};
}

.widget-dnd > switch {
  border-radius: 12px;
  background: {{COLOR_SURFACE}};
}

.widget-dnd > switch:checked {
  background: {{COLOR_PRIMARY}};
}

.widget-buttons-grid > flowbox > flowboxchild > button {
  background: {{COLOR_SURFACE}};
  color: {{COLOR_FG}};
  border-radius: 10px;
  padding: 8px;
  margin: 4px;
  border: 1px solid transparent;
  transition: all 0.2s ease;
}

.widget-buttons-grid > flowbox > flowboxchild > button:hover {
  background: {{COLOR_PRIMARY}};
  color: {{COLOR_BG}};
  border-color: {{COLOR_PRIMARY}};
}

.widget-buttons-grid > flowbox > flowboxchild > button.toggle:checked {
  background: {{COLOR_ACCENT}};
  color: {{COLOR_BG}};
}
