# sysdx config — Generated by theme system, do not edit manually

[display]
journal_lines    = 60
tick_rate_ms     = 250
show_description = true
list_width_pct   = 38
date_format      = "%H:%M:%S"

[keybinds]
move_down    = "j"
move_up      = "k"
page_down    = "ctrl-d"
page_up      = "ctrl-u"
go_top       = "g"
go_bottom    = "G"
filter       = "/"
action_menu  = "enter"
switch_scope = "tab"
open_logs    = "l"
quit         = "q"

[colors]
background     = "{{COLOR_BG}}"
surface        = "{{COLOR_BG_ALT}}"
border         = "{{COLOR_BORDER}}"
border_focused = "{{COLOR_ACCENT}}"
text           = "{{COLOR_FG}}"
text_dim       = "{{COLOR_FG_DIM}}"
selection_bg   = "{{COLOR_SURFACE}}"
selection_fg   = "{{COLOR_FG}}"
active         = "{{COLOR_ACCENT}}"
inactive       = "{{COLOR_FG_DIM}}"
failed         = "{{COLOR_CRIT}}"
filter_bar     = "{{COLOR_WARN}}"
header         = "{{COLOR_PRIMARY}}"
