# tmux theme — Generated by theme system (do not edit)

# Status bar
set -g status-style "bg={{COLOR_BG}},fg={{COLOR_FG_DIM}}"
set -g status-left "#[bg={{COLOR_PRIMARY}},fg={{COLOR_BG}},bold]  #S #[bg={{COLOR_BG}},fg={{COLOR_PRIMARY}}]"
setw -g window-status-style "bg={{COLOR_BG}},fg={{COLOR_SURFACE}}"
setw -g window-status-format "#[bg={{COLOR_BG_ALT}},fg={{COLOR_FG_DIM}}] #I #[bg={{COLOR_BG}},fg={{COLOR_BG_ALT}}]#[fg={{COLOR_FG_DIM}}] #W "
setw -g window-status-current-style "bg={{COLOR_SECONDARY}},fg={{COLOR_BG}},bold"
setw -g window-status-current-format "#[bg={{COLOR_SECONDARY}},fg={{COLOR_BG}}] #I #[bg={{COLOR_BG}},fg={{COLOR_SECONDARY}}]#[fg={{COLOR_SECONDARY}},bold] #W #[bg={{COLOR_BG}},fg={{COLOR_SECONDARY}}]"
set -g status-right "#[fg={{COLOR_PINK}}]#[bg={{COLOR_PINK}},fg={{COLOR_BG}}]  %H:%M #[bg={{COLOR_BG}},fg={{COLOR_PINK}}]#[fg={{COLOR_ACCENT}}]#[bg={{COLOR_ACCENT}},fg={{COLOR_BG}}]  %d-%m-%Y #[bg={{COLOR_BG}},fg={{COLOR_ACCENT}}]#[fg={{COLOR_PRIMARY}}]#[bg={{COLOR_PRIMARY}},fg={{COLOR_BG}}]  #H #[bg={{COLOR_BG}},fg={{COLOR_PRIMARY}}]"

# Panes
set -g pane-border-style "fg={{COLOR_SURFACE}}"
set -g pane-active-border-style "fg={{COLOR_SECONDARY}},bold"
set -g display-panes-colour "{{COLOR_FG_DIM}}"
set -g display-panes-active-colour "{{COLOR_ACCENT}}"

# Messages
set -g message-style "bg={{COLOR_PRIMARY}},fg={{COLOR_BG}},bold"
set -g message-command-style "bg={{COLOR_BG_ALT}},fg={{COLOR_SECONDARY}}"
setw -g mode-style "bg={{COLOR_PINK}},fg={{COLOR_BG}}"
