/* Waybar color definitions — Generated by theme system */
/* GTK CSS uses @define-color, not :root/--var */
@define-color color_bg {{COLOR_BG}};
@define-color color_bg_alt {{COLOR_BG_ALT}};
@define-color color_fg {{COLOR_FG}};
@define-color color_fg_dim {{COLOR_FG_DIM}};
@define-color color_primary {{COLOR_PRIMARY}};
@define-color color_secondary {{COLOR_SECONDARY}};
@define-color color_accent {{COLOR_ACCENT}};
@define-color color_border {{COLOR_BORDER}};
@define-color color_warn {{COLOR_WARN}};
@define-color color_crit {{COLOR_CRIT}};
@define-color color_surface {{COLOR_SURFACE}};
@define-color color_pink {{COLOR_PINK}};
