/* wlogout style — Generated by theme system */
window {
  background-color: rgba(0, 0, 0, 0.5);
}

button {
  background-color: {{COLOR_BG_ALT}};
  color: {{COLOR_FG}};
  border: 2px solid {{COLOR_SURFACE}};
  border-radius: 16px;
  margin: 10px;
  padding: 20px;
  font-size: 18px;
  transition: all 0.3s ease;
  background-repeat: no-repeat;
  background-position: center;
  background-size: 48px;
}

button:hover {
  background-color: {{COLOR_PRIMARY}};
  color: {{COLOR_BG}};
  border-color: {{COLOR_PRIMARY}};
  box-shadow: 0 0 20px {{COLOR_PRIMARY}};
}

button:focus {
  background-color: {{COLOR_SECONDARY}};
  color: {{COLOR_BG}};
  border-color: {{COLOR_SECONDARY}};
}

#lock {
  background-image: image(url("/usr/share/wlogout/icons/lock.png"));
}

#logout {
  background-image: image(url("/usr/share/wlogout/icons/logout.png"));
}

#suspend {
  background-image: image(url("/usr/share/wlogout/icons/suspend.png"));
}

#hibernate {
  background-image: image(url("/usr/share/wlogout/icons/hibernate.png"));
}

#shutdown {
  background-image: image(url("/usr/share/wlogout/icons/shutdown.png"));
}

#reboot {
  background-image: image(url("/usr/share/wlogout/icons/reboot.png"));
}
